# Artificial Neural Network for Self-Driving Car

UPDATE - NEW IMAGE SIZES ARE NOW 18X22 (396)

UPDATE 2 - Just dome information for you
    - I can now implement classes and OOP in my program
    - I can turn my whole data preprocessing code into a class to be used multiple times

Plan of Attack:
    - Import all images from training set:
        - Forward, Left and Right Folders
    - Resize all the images to 18x22
    - Convert images to greyscale:
        - Placing the new images in a new array
    - Now Reshaping to create a new array which contains flattened images (6336)
        - Shape now (3000, 396)
    - Add the appropirate labels to each data
    - Shuffle the 3 image arrays and the 3 label array corresondingly
    - Append all three arrays to a new array:
        - One containing all image data
        - One containing all labelled data
    - Init all TensorFlow variables and constants
    - Start an Interative Session
    - Start the training:
        - Make sure to add saving capabilities
    - Once trained and saved - YOU HAVE YOUR MODEL!!!!

In [1]:
import tensorflow as tf                    #Machine Learning Library
import matplotlib.pyplot as plt            #Display the images for verification
import numpy as np                         #Mathematical and arrays library
from scipy import misc                     #Image Importing module
from skimage.transform import resize       #Resizing image module
from sklearn.utils import shuffle          #Shuffle in random order module
import glob                                #Iterating through all pictures library

### Greyscale Conversion Method

In [2]:
def weightedAverage(pixel):
    return 0.299*pixel[0] + 0.587*pixel[1] + 0.114*pixel[2]

### Forward Array image importing / resizing / convert / reshape / labelling / shuffleing

In [3]:
#Creating initial array and resizing
f_image_list = []
img_count = 0
path = "/Users/hannansaleemi/Desktop/SDC/Jupyter Notebook Examples/cardataset/training_set/Forward/"
for filename in glob.glob(path+'*.png'):
    img_count += 1
    image = misc.imread(path+'trainframe ('+str(img_count)+').png')
    image_resized = resize(image, (18,22), mode='reflect')
    f_image_list.append(image_resized)

In [4]:
#Just confiming the shape of the array
print(image_resized.shape)

NameError: name 'image_resized' is not defined

In [5]:
#Converting to greyscale
f_grey = np.zeros((3000, image_resized.shape[0], image_resized.shape[1]))

for image_num in range(len(f_image_list)):
    for rownum in range(len(f_image_list[image_num])):
        for colnum in range(len(f_image_list[image_num][rownum])):
            f_grey[image_num][rownum][colnum] = weightedAverage(f_image_list[image_num][rownum][colnum])
    #Output Logging
    if image_num % 100 == 0:
        print("Finished converting image #", (image_num))

NameError: name 'image_resized' is not defined

In [6]:
#Just checking the shape of the greyscale array
f_grey.shape

NameError: name 'f_grey' is not defined

In [7]:
#Reshaping
f_images = f_grey.reshape(3000,396)

In [8]:
#Just checking the new shape again
f_images.shape

(3000, 396)

In [9]:
#Creating Labels
f_labels = np.zeros(shape=(3000,3))

#Adding 3000 forward labels [1,0,0]
for i in range(3000):
    f_labels[i][0] = float(1)

In [10]:
#Just checking the labels
f_labels

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       ..., 
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]])

In [11]:
#Shuffling the images
f_images, f_labels = shuffle(f_images, f_labels, random_state = 4000)

In [12]:
#Checking if they have shuffled
f_images

array([[ 0.20488431,  0.31913235,  0.40438627, ...,  0.93290392,
         0.91115392,  0.90059118],
       [ 0.16452059,  0.23098333,  0.24517451, ...,  0.45037843,
         0.64341667,  0.86788725],
       [ 0.52245294,  0.53974706,  0.56372451, ...,  0.88922059,
         0.87743824,  0.86189804],
       ..., 
       [ 0.12021863,  0.10482941,  0.12077941, ...,  0.52446667,
         0.47657353,  0.7271    ],
       [ 0.55091176,  0.57213137,  0.62195784, ...,  0.89393235,
         0.88511961,  0.87136176],
       [ 0.06414314,  0.05195686,  0.09219804, ...,  0.61300686,
         0.5555402 ,  0.49911863]])

### Forward Images Done:
    - f_images - contain images
    - f_lables - contain labels

### Left Array image importing / resizing / convert / reshape / labelling / shuffleing

In [13]:
#Creating initial array and resizing
l_image_list = []
img_count = 0
path = "/Users/hannansaleemi/Desktop/SDC/Jupyter Notebook Examples/cardataset/training_set/Left/"
for filename in glob.glob(path+'*.png'):
    img_count += 1
    image = misc.imread(path+'trainframe ('+str(img_count)+').png')
    image_resized = resize(image, (18,22), mode='reflect')
    l_image_list.append(image_resized)

In [14]:
#Just confiming the shape of the array
print(image_resized.shape)

(18, 22, 3)


In [15]:
#Converting to greyscale
l_grey = np.zeros((3000, image_resized.shape[0], image_resized.shape[1]))

for image_num in range(len(l_image_list)):
    for rownum in range(len(l_image_list[image_num])):
        for colnum in range(len(l_image_list[image_num][rownum])):
            l_grey[image_num][rownum][colnum] = weightedAverage(l_image_list[image_num][rownum][colnum])
    #Output Logging
    if image_num % 100 == 0:
        print("Finished converting image #", (image_num))

Finished converting image # 0
Finished converting image # 100
Finished converting image # 200
Finished converting image # 300
Finished converting image # 400
Finished converting image # 500
Finished converting image # 600
Finished converting image # 700
Finished converting image # 800
Finished converting image # 900
Finished converting image # 1000
Finished converting image # 1100
Finished converting image # 1200
Finished converting image # 1300
Finished converting image # 1400
Finished converting image # 1500
Finished converting image # 1600
Finished converting image # 1700
Finished converting image # 1800
Finished converting image # 1900
Finished converting image # 2000
Finished converting image # 2100
Finished converting image # 2200
Finished converting image # 2300
Finished converting image # 2400
Finished converting image # 2500
Finished converting image # 2600
Finished converting image # 2700
Finished converting image # 2800
Finished converting image # 2900


In [16]:
#Just checking the shape of the greyscale array
l_grey.shape

(3000, 18, 22)

In [17]:
#Reshaping
l_images = l_grey.reshape(3000,396)

In [18]:
#Just checking the new shape again
l_images.shape

(3000, 396)

In [19]:
#Creating Labels
l_labels = np.zeros(shape=(3000,3))

#Adding 3000 forward labels [1,0,0]
for i in range(3000):
    l_labels[i][1] = float(1)

In [20]:
#Just checking the labels
l_labels

array([[ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       ..., 
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.]])

In [21]:
#Shuffling the images
l_images, l_labels = shuffle(l_images, l_labels, random_state = 4000)

In [22]:
#Checking if they have shuffled
f_images

array([[ 0.20488431,  0.31913235,  0.40438627, ...,  0.93290392,
         0.91115392,  0.90059118],
       [ 0.16452059,  0.23098333,  0.24517451, ...,  0.45037843,
         0.64341667,  0.86788725],
       [ 0.52245294,  0.53974706,  0.56372451, ...,  0.88922059,
         0.87743824,  0.86189804],
       ..., 
       [ 0.12021863,  0.10482941,  0.12077941, ...,  0.52446667,
         0.47657353,  0.7271    ],
       [ 0.55091176,  0.57213137,  0.62195784, ...,  0.89393235,
         0.88511961,  0.87136176],
       [ 0.06414314,  0.05195686,  0.09219804, ...,  0.61300686,
         0.5555402 ,  0.49911863]])

### Left Images Done:
    - l_images - contain images
    - l_lables - contain labels

### Right Array image importing / resizing / convert / reshape / labelling / shuffleing

In [23]:
#Creating initial array and resizing
r_image_list = []
img_count = 0
path = "/Users/hannansaleemi/Desktop/SDC/Jupyter Notebook Examples/cardataset/training_set/Right/"
for filename in glob.glob(path+'*.png'):
    img_count += 1
    image = misc.imread(path+'trainframe ('+str(img_count)+').png')
    image_resized = resize(image, (18,22), mode='reflect')
    r_image_list.append(image_resized)

In [24]:
#Just confiming the shape of the array
print(image_resized.shape)

(18, 22, 3)


In [25]:
#Converting to greyscale
r_grey = np.zeros((3000, image_resized.shape[0], image_resized.shape[1]))

for image_num in range(len(r_image_list)):
    for rownum in range(len(r_image_list[image_num])):
        for colnum in range(len(r_image_list[image_num][rownum])):
            r_grey[image_num][rownum][colnum] = weightedAverage(r_image_list[image_num][rownum][colnum])
    #Output Logging
    if image_num % 100 == 0:
        print("Finished converting image #", (image_num))

Finished converting image # 0
Finished converting image # 100
Finished converting image # 200
Finished converting image # 300
Finished converting image # 400
Finished converting image # 500
Finished converting image # 600
Finished converting image # 700
Finished converting image # 800
Finished converting image # 900
Finished converting image # 1000
Finished converting image # 1100
Finished converting image # 1200
Finished converting image # 1300
Finished converting image # 1400
Finished converting image # 1500
Finished converting image # 1600
Finished converting image # 1700
Finished converting image # 1800
Finished converting image # 1900
Finished converting image # 2000
Finished converting image # 2100
Finished converting image # 2200
Finished converting image # 2300
Finished converting image # 2400
Finished converting image # 2500
Finished converting image # 2600
Finished converting image # 2700
Finished converting image # 2800
Finished converting image # 2900


In [26]:
#Just checking the shape of the greyscale array
r_grey.shape

(3000, 18, 22)

In [27]:
#Reshaping
r_images = r_grey.reshape(3000,396)

In [28]:
#Just checking the new shape again
r_images.shape

(3000, 396)

In [29]:
#Creating Labels
r_labels = np.zeros(shape=(3000,3))

#Adding 3000 forward labels [1,0,0]
for i in range(3000):
    r_labels[i][2] = float(1)

In [30]:
#Just checking the labels
r_labels

array([[ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       ..., 
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.]])

In [31]:
#Shuffling the images
r_images, r_labels = shuffle(r_images, r_labels, random_state = 4000)

In [32]:
#Checking if they have shuffled
r_images

array([[ 0.42381863,  0.24559314,  0.33323431, ...,  0.32286176,
         0.35372255,  0.37860392],
       [ 0.53156373,  0.61470882,  0.64574902, ...,  0.83415686,
         0.89350784,  0.86481569],
       [ 0.24203922,  0.24657549,  0.21022059, ...,  0.54228235,
         0.54340196,  0.52687745],
       ..., 
       [ 0.28160098,  0.28735686,  0.29853725, ...,  0.21704412,
         0.20153922,  0.18539902],
       [ 0.29032451,  0.30502255,  0.33215882, ...,  0.56873725,
         0.56399216,  0.84679706],
       [ 0.66723333,  0.52322941,  0.17988235, ...,  0.56154608,
         0.55193627,  0.51371471]])

### Right Images Done:
    - r_images - contain images
    - r_lables - contain labels

## Merging all images and labels together into 2 seperate arrays

In [33]:
all_images_array = np.concatenate((f_images, l_images, r_images), axis=0)

In [34]:
all_labels_array = np.concatenate((f_labels, l_labels, r_labels), axis=0)

## Shuffle array to randomize order

In [35]:
#Checking states before
all_images_array

array([[ 0.20488431,  0.31913235,  0.40438627, ...,  0.93290392,
         0.91115392,  0.90059118],
       [ 0.16452059,  0.23098333,  0.24517451, ...,  0.45037843,
         0.64341667,  0.86788725],
       [ 0.52245294,  0.53974706,  0.56372451, ...,  0.88922059,
         0.87743824,  0.86189804],
       ..., 
       [ 0.28160098,  0.28735686,  0.29853725, ...,  0.21704412,
         0.20153922,  0.18539902],
       [ 0.29032451,  0.30502255,  0.33215882, ...,  0.56873725,
         0.56399216,  0.84679706],
       [ 0.66723333,  0.52322941,  0.17988235, ...,  0.56154608,
         0.55193627,  0.51371471]])

In [36]:
#Checking states before
all_labels_array

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       ..., 
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.]])

In [37]:
#Shuffling the images
all_images_array, all_labels_array = shuffle(all_images_array, all_labels_array, random_state = 9000)

In [38]:
#Rechecking states
all_images_array

array([[ 0.62003333,  0.52430588,  0.68951275, ...,  0.52891176,
         0.48937647,  0.66167353],
       [ 0.31736471,  0.34797255,  0.32738529, ...,  0.62466667,
         0.56809804,  0.55606569],
       [ 0.04113922,  0.13658039,  0.16118039, ...,  0.47372941,
         0.44008039,  0.38227353],
       ..., 
       [ 0.61493627,  0.48115686,  0.42215098, ...,  0.66561863,
         0.61916667,  0.57276275],
       [ 0.58308529,  0.58470098,  0.55935392, ...,  0.59097059,
         0.52669706,  0.56237059],
       [ 0.25593529,  0.35657843,  0.32090294, ...,  0.83862549,
         0.82238235,  0.80096667]])

In [39]:
#Rechecking states
all_labels_array

array([[ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       ..., 
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.]])

# Shuffling Complete Data Set Complete
     - all_images_array - contains image data
     - all_labels_array - contains label data

# Moving on to TensorFlow

# Defining Parameters:

Parameters:
    - Learning Rate - How quickly we adjust the cost function (tradeoff by setting it to very small vs setting is veyr big)
    - Number of epochs - How many training cycles to go through - going through the same data over and over again
    - Batch Size - sizes of the training data

In [40]:
#learning_rate = 0.001
learning_rate = 0.0001
#training_epochs = 15
training_epochs = 25
batch_size = 640

Network Parameters: - Define what the NN or Multi-Layer Perceptron looks like:
    - n_classes - ten types of inputs and outputs (0-9)
    - n_samples - number of samples in the training data (55000) - can get the number by 'mnist.train.num_examples'
    - n_input - what we expect the input to look like - 28x28 flattened vector so 784 inputs going in
    - The model will have 2 hidden layers each with 256 nodes:
        - n_hidden_1 - number of nuerons in hidden layer 1
        - n_hidden_2 - number of neurons in hidden layer 2

Why 256?
    - Computers have a way of storing image information as 8 bit color storage

In [41]:
n_classes = 3
#n_samples = 9000
n_samples = 9000
n_input = 396
n_hidden_1 = 256
n_hidden_2 = 256

Plan of Attack:
    - First, Recieve input image data array
    - Send it to the first hidden layer with weights multiplied and a bias
    - Sent to next hidden layer with weights multiplied
    - Then sent to output layer
    - Calculate the error - Loss Function or Cost Function - How far off the desired result we are?
    - Apply optimisation function to try and minimise the cost/error
        - This is done by adjusting the weights accordingly across the whole network
        - We will be using the adam optimiser
            - This depends on the learning rate - the lower the rate, the higher the accuracy but really slow to reach target and after a certian amaount of time - there is no point to lower cost as it has already reached minimum
            - The higher the rate, low accuracy, may never converge, may bouce around accuracy

## Creating a function for a multi-layer perceptron:

INFO:
RELU Activtaion function - good from images - rectifier function - either returns an x or 0 - whichever is greater
Output layer Activation Function - Linear activation function - matrix multiplication
2 hidden layers

This function will take 3 arguments:
    - x
    - Weights
    - biases

So in the first layer:
    - Mutiply all the x and weight values toghether (h1 contains weights for hidden layer 1) (NEEDS TO MATRIX MULTIPLY ALWAYS)
    - The add all of the values of each x * weight and the bias summed together.
    - Then we pass the value into the RELU Function
        - What RELU does: f(x) = max(0,x)
        
The same as above is going on in the second layer

In [42]:
def multilayer_perceptron(x, weights,biases):
    '''
    x: Placeholder for Data Input
    weights: Dict of weights
    biases: dict of bias values
    '''
    
    ### First Hidden Layer with RELU Activation Function
    # X * W + B
    layer_1 = tf.add(tf.matmul(x,weights['h1']),biases['b1'])
    # RELU(X * W + B) -> f(x) = max(0,x)
    layer_1 = tf.nn.relu(layer_1)
    
    ### Last Output Layer
    out_layer = tf.matmul(layer_1,weights['out']) + biases['out']
    
    return out_layer

## Weights

We will now introduce tensorflow variables - This is a modifiable value, can even be modified by computation graph

Generally, Model parameter are tensorflow variables

REMEMBER: Weights are random to start off with, they will be fined tuned by the NN when calculating the cost/error

tf.random_normal - outputs random values from a normal distribution - used to randomly initialise
    - tf.random.normal([row, columns]) - creates a matrix of random values, with certain number of rows and columns

WHY IS A MATRIX? HOW WILL THE VALUES GET ASSIGNED?
    - So the input is 784 different pixel values and the next layer is made of 256 neurons. Each neuron in the input layer will
      be connected to all neurons in the next layer and therefore there will be 784*256 weights, therefore assigning each 
      branch with a weight.

In [43]:
#Creating the weights dictionary
'''
    h1 - martix of randomly assigned values from a normal distribution. rows=784, columns=256
    h2 - martix of randomly assigned values from a normal distribution. rows=256, columns=256
    out - matric of randomly assigned values from a normal distribution. rows=256, columns=10
'''
weights = {
    'h1':tf.Variable(tf.random_normal([n_input, n_hidden_1])),
    'out':tf.Variable(tf.random_normal([n_hidden_1,n_classes]))
}

WAIT! What will the output look like:
    - Well remeber above we set one-hot to true
    - so 0 is represented as [1 0 0 0 0 0 0 0 0 0]
         1 is represented as [0 1 0 0 0 0 0 0 0 0]
         etc...
    - So the output will also be an array like this 
      EG) it predicts it is 4 so output will be [0 0 0 0 1 0 0 0 0 0]

## Biases:

Biases are are the same size as the layer

In [44]:
biases = {
    'b1':tf.Variable(tf.random_normal([n_hidden_1])),
    'out':tf.Variable(tf.random_normal([n_classes])) 
}

Now we will set two placeholders for x and y

x - The same size as the input as the input is 784 array

y - output - will be a 10 element array as there are only 10 outputs

In [45]:
x = tf.placeholder('float', [None, n_input])

In [46]:
y = tf.placeholder('float',[None,n_classes])

## Setting up the model:

In [47]:
pred = multilayer_perceptron(x,weights,biases)

## Define cost and optimiser functions

We will use built in tensorflow functions for these parts

In [48]:
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred,labels=y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

# Training The Model:

Training Stage:

## Running the Session :)

In [49]:
config = tf.ConfigProto()
config.gpu_options.allow_growth=True

In [50]:
sess = tf.InteractiveSession(config=config)

In [51]:
init = tf.global_variables_initializer()

In [52]:
saver = tf.train.Saver()

In [53]:
sess.run(init)

Lets now actually train the model for the number of epochs we defines (15):

More Info:
    - So basically we get the total batch - 550
    - Next we extract the x = the image data and the y = the label for those images correspondingly
    - Do the training for that epoch and return the cost
    - At the end of 15 loops/epochs - the model has been trained on the data

In [54]:
start_batch = 0
end_batch = batch_size

for epoch in range(training_epochs):
    
    #Cost
    avg_cost = 0.0
    
    #Define total_batch as an integer
    #9000/100 = 90
    total_batch = int(n_samples/batch_size)
    
    for i in range(total_batch):
        # Grab the next batch of data using the batch explaination i did above ^^^
        #batch_x, batch_y = mnist.train.next_batch(batch_size)
        
        batch_x = all_images_array[start_batch:end_batch]
        batch_y = all_labels_array[start_batch:end_batch]
        
        #Optimisation and Loss values - the '_' is a unwanted variable for tuple unpacking
        #This will return a loss - which is assigned to 'c'
        _, c = sess.run([optimizer, cost], feed_dict={x:batch_x, y:batch_y})
        
        avg_cost += c/total_batch
        
        start_batch += batch_size
        end_batch += batch_size
        
    print("Epoch: {} Cost {:.4f}".format(epoch+1,avg_cost))

print("Model has completed {} Epochs of training".format(training_epochs))

Epoch: 1 Cost 37.2280
Epoch: 2 Cost nan
Epoch: 3 Cost nan
Epoch: 4 Cost nan
Epoch: 5 Cost nan
Epoch: 6 Cost nan
Epoch: 7 Cost nan
Epoch: 8 Cost nan
Epoch: 9 Cost nan
Epoch: 10 Cost nan
Epoch: 11 Cost nan
Epoch: 12 Cost nan
Epoch: 13 Cost nan
Epoch: 14 Cost nan
Epoch: 15 Cost nan
Epoch: 16 Cost nan
Epoch: 17 Cost nan
Epoch: 18 Cost nan
Epoch: 19 Cost nan
Epoch: 20 Cost nan
Epoch: 21 Cost nan
Epoch: 22 Cost nan
Epoch: 23 Cost nan
Epoch: 24 Cost nan
Epoch: 25 Cost nan
Model has completed 25 Epochs of training


In [55]:
save_path = saver.save(sess, "C:/Users/Hannan Saleemi/Documents/model.ckpt")

ValueError: Parent directory of C:/Users/Hannan Saleemi/Documents/model.ckpt doesn't exist, can't save.

In [ ]:
correct_predictions = tf.equal(tf.argmax(pred,1),tf.argmax(y,1))

In [ ]:
correct_predictions = tf.cast(correct_predictions, 'float')

In [ ]:
accuracy = tf.reduce_mean(correct_predictions)

In [ ]:
accuracy.eval({x: all_images_array, y: all_labels_array})

# SO WHAT HAS HAPPENED?

    - So far i keep getting the GPU ran out of memory error (Resource Exhausted)
        - To solve this either reduce batch size or reduce number of epochs - i had to do both
    - The cost keeps bouncing around - maybe more layers needed / lower learning rat
    - The model is evaluated on the training data - same data as trained on giving a 0.998667% accuracy
    
    - Maybe increase batch size and increase epochs
    - or decarese batch size and increase epochs
    - play around to avoid GPU Memory Error

# Apparently - i can reset GPU Memory anytime by calling this function:

Best to reset GPU Memory after 8 epochs
DOESN'T WORK - K is not defined!!!

In [ ]:
def reset_GPU_mem():
    K.get_session()
    cfg = K.tf.ConfigProto()
    cfg.gpu_options.allow.growth = True
    K.set_session(K.tf.Session(config=cfg))

# Lets test a prediction method

In [ ]:
array_test = np.zeros(shape=(396))
array_test = all_images_array[2400].reshape(1,396)

In [ ]:
result = sess.run(tf.argmax(pred, 1), feed_dict={x: array_test})
if result == [2]:
    print("Model has predicted: Right")
elif result == [1]:
    print("Model has predicted: Left")
elif result == [0]:
    print("Model has predicted: Forward")

In [ ]:
draw_img = all_images_array[2400].reshape(18,22)

In [ ]:
plt.imshow(draw_img, cmap='Greys')
plt.show()